// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/SMS/send": {
            "get": {
                "description": "Sent verification code",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SMS"
                ],
                "summary": "SentVerificationCode",
                "parameters": [
                    {
                        "type": "string",
                        "format": "18888888888",
                        "example": "18888888888",
                        "description": "Phone number",
                        "name": "phone_number",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseSuccess-interceptor_Empty"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    }
                }
            }
        },
        "/user/approveRegistration": {
            "get": {
                "description": "Approve user registration",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "ApproveRegistration",
                "parameters": [
                    {
                        "type": "string",
                        "example": "1",
                        "description": "User id",
                        "name": "cid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "{{token}}",
                        "description": "Authorization token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseSuccess-interceptor_Empty"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    }
                }
            }
        },
        "/user/checkName": {
            "get": {
                "description": "check username availability",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "CheckName",
                "parameters": [
                    {
                        "maxLength": 10,
                        "minLength": 5,
                        "type": "string",
                        "format": "luolayo",
                        "example": "luolayo",
                        "description": "Username",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseSuccess-interceptor_Empty"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    }
                }
            }
        },
        "/user/checkPhone": {
            "get": {
                "description": "check phone number availability",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "CheckPhone",
                "parameters": [
                    {
                        "type": "string",
                        "format": "18888888888",
                        "example": "18888888888",
                        "description": "UserPhone",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseSuccess-interceptor_Empty"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    }
                }
            }
        },
        "/user/getUserInfoById": {
            "get": {
                "description": "Get user information by id",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "GetUserInfoById",
                "parameters": [
                    {
                        "type": "string",
                        "example": "1",
                        "description": "User id",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "{{token}}",
                        "description": "Authorization token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseSuccess-model_User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    }
                }
            }
        },
        "/user/getUserList": {
            "get": {
                "description": "Get user list",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "GetUserList",
                "parameters": [
                    {
                        "type": "string",
                        "example": "{{token}}",
                        "description": "Authorization token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseSuccess-array_model_User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    }
                }
            }
        },
        "/user/info": {
            "get": {
                "description": "Get user information",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "UserInfo",
                "parameters": [
                    {
                        "type": "string",
                        "example": "{{token}}",
                        "description": "Authorization token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseSuccess-model_User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "User login",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "UserLogin",
                "parameters": [
                    {
                        "description": "User login data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseSuccess-model_User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    }
                }
            }
        },
        "/user/logout": {
            "get": {
                "description": "User logout",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "UserLogout",
                "parameters": [
                    {
                        "type": "string",
                        "example": "{{token}}",
                        "description": "Authorization token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseSuccess-interceptor_Empty"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "Register user",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "RegisterUser",
                "parameters": [
                    {
                        "description": "User registration data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserRegister"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseSuccess-model_User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    }
                }
            }
        },
        "/user/updateUserInfo": {
            "post": {
                "description": "Update user information",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "UpdateUserInfo",
                "parameters": [
                    {
                        "description": "User update data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserUpdate"
                        }
                    },
                    {
                        "type": "string",
                        "example": "{{token}}",
                        "description": "Authorization token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseSuccess-model_User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    }
                }
            }
        },
        "/user/updateUserPassword": {
            "post": {
                "description": "Update user password",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "UpdateUserPassword",
                "parameters": [
                    {
                        "type": "string",
                        "example": "{{token}}",
                        "description": "Authorization token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "maxLength": 20,
                        "minLength": 6,
                        "type": "string",
                        "example": "123456",
                        "description": "New password",
                        "name": "newPassword",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "123456",
                        "description": "Verification code",
                        "name": "code",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseSuccess-interceptor_Empty"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    }
                }
            }
        },
        "/user/updateUserPhone": {
            "post": {
                "description": "Update user phone number",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "UpdateUserPhone",
                "parameters": [
                    {
                        "type": "string",
                        "example": "{{token}}",
                        "description": "Authorization token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "18888888888",
                        "example": "18888888888",
                        "description": "Phone number",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "123456",
                        "description": "Verification code",
                        "name": "code",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseSuccess-interceptor_Empty"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/interceptor.ResponseError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "interceptor.Empty": {
            "type": "object"
        },
        "interceptor.ResponseError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "err": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Invalid request"
                }
            }
        },
        "interceptor.ResponseSuccess-array_model_User": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.User"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Success"
                }
            }
        },
        "interceptor.ResponseSuccess-interceptor_Empty": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/interceptor.Empty"
                },
                "message": {
                    "type": "string",
                    "example": "Success"
                }
            }
        },
        "interceptor.ResponseSuccess-model_User": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/model.User"
                },
                "message": {
                    "type": "string",
                    "example": "Success"
                }
            }
        },
        "model.Group": {
            "type": "string",
            "enum": [
                "admin",
                "user",
                "guest"
            ],
            "x-enum-varnames": [
                "GroupAdmin",
                "GroupUser",
                "GroupGuest"
            ]
        },
        "model.User": {
            "type": "object",
            "properties": {
                "activated": {
                    "description": "User activation time",
                    "type": "string",
                    "example": "2021-07-01 00:00:00"
                },
                "group": {
                    "description": "User group",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Group"
                        }
                    ]
                },
                "logged": {
                    "description": "User last login time",
                    "type": "string",
                    "example": "2021-07-01 00:00:00"
                },
                "name": {
                    "description": "User name",
                    "type": "string",
                    "example": "admin"
                },
                "phone": {
                    "description": "User phone number",
                    "type": "string",
                    "example": "18888888888"
                },
                "screenName": {
                    "description": "User nickname",
                    "type": "string",
                    "example": "罗拉"
                },
                "token": {
                    "description": "User token",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsIm5hbWUiOiJhZG1pbiIsImV4cCI6MTYyNjMwNzQwMCwiaWF0IjoxNjI2MzA3MjAwfQ"
                },
                "uid": {
                    "description": "User ID",
                    "type": "integer",
                    "example": 1
                },
                "url": {
                    "description": "User url",
                    "type": "string",
                    "example": "https://www.luola.me"
                }
            }
        },
        "model.UserLogin": {
            "type": "object",
            "required": [
                "name",
                "password"
            ],
            "properties": {
                "name": {
                    "description": "User name",
                    "type": "string",
                    "example": "admin"
                },
                "password": {
                    "description": "User password",
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "model.UserRegister": {
            "type": "object",
            "required": [
                "code",
                "confirmPassword",
                "name",
                "password",
                "phone"
            ],
            "properties": {
                "code": {
                    "description": "Verification code",
                    "type": "string",
                    "example": "123456"
                },
                "confirmPassword": {
                    "description": "Confirm password is the same as password",
                    "type": "string",
                    "example": "123456"
                },
                "name": {
                    "description": "User name",
                    "type": "string",
                    "example": "admin"
                },
                "password": {
                    "description": "User password",
                    "type": "string",
                    "example": "123456"
                },
                "phone": {
                    "description": "User phone number",
                    "type": "string",
                    "example": "18888888888"
                },
                "screenName": {
                    "description": "User nickname",
                    "type": "string",
                    "example": "罗拉"
                },
                "url": {
                    "description": "User avatar",
                    "type": "string",
                    "example": "https://www.luola.me"
                }
            }
        },
        "model.UserUpdate": {
            "type": "object",
            "properties": {
                "screenName": {
                    "description": "User nickname",
                    "type": "string",
                    "example": "罗拉"
                },
                "url": {
                    "description": "User url",
                    "type": "string",
                    "example": "https://www.luola.me"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.1",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Gin Study API",
	Description:      "Gin study is a small project for beginners to learn by writing a blog built by the gin framework.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
