basePath: /
definitions:
  interceptor.Empty:
    type: object
  interceptor.ResponseError:
    properties:
      code:
        type: integer
      err:
        items:
          type: string
        type: array
      message:
        type: string
    type: object
  interceptor.ResponseSuccess-interceptor_Empty:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/interceptor.Empty'
      message:
        type: string
    type: object
  interceptor.ResponseSuccess-model_User:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/model.User'
      message:
        type: string
    type: object
  model.Group:
    enum:
    - admin
    - user
    - guest
    type: string
    x-enum-varnames:
    - GroupAdmin
    - GroupUser
    - GroupGuest
  model.User:
    properties:
      group:
        $ref: '#/definitions/model.Group'
      logged:
        type: string
      name:
        type: string
      phone:
        type: string
      screenName:
        type: string
      token:
        type: string
      uid:
        type: integer
      url:
        type: string
    type: object
  model.UserLogin:
    properties:
      name:
        example: admin
        type: string
      password:
        example: "123456"
        type: string
    required:
    - name
    - password
    type: object
  model.UserRegister:
    properties:
      code:
        example: "123456"
        type: string
      confirmPassword:
        example: "123456"
        type: string
      name:
        example: admin
        type: string
      password:
        example: "123456"
        type: string
      phone:
        example: "18888888888"
        type: string
      screenName:
        example: 罗拉
        type: string
      url:
        example: https://www.luola.me
        type: string
    required:
    - code
    - confirmPassword
    - name
    - password
    - phone
    type: object
host: localhost:8080
info:
  contact: {}
  description: Gin study is a small project for beginners to learn by writing a blog
    built by the gin framework.
  title: Gin Study API
  version: 1.0.1
paths:
  /SMS/send:
    get:
      description: Sent verification code
      parameters:
      - description: Phone number
        example: "18888888888"
        format: "18888888888"
        in: query
        name: phone_number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interceptor.ResponseSuccess-interceptor_Empty'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/interceptor.ResponseError'
      summary: SentVerificationCode
      tags:
      - SMS
  /user/checkName:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: check username availability
      parameters:
      - description: Username
        example: luolayo
        format: luolayo
        in: query
        maxLength: 10
        minLength: 5
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interceptor.ResponseSuccess-interceptor_Empty'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/interceptor.ResponseError'
      summary: CheckName
      tags:
      - User
  /user/checkPhone:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: check phone number availability
      parameters:
      - description: UserPhone
        example: "18888888888"
        format: "18888888888"
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interceptor.ResponseSuccess-interceptor_Empty'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/interceptor.ResponseError'
      summary: CheckPhone
      tags:
      - User
  /user/info:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Get user information
      parameters:
      - description: Authorization token
        example: '{{token}}'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interceptor.ResponseSuccess-model_User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/interceptor.ResponseError'
      summary: UserInfo
      tags:
      - User
  /user/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: User login
      parameters:
      - description: User login data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interceptor.ResponseSuccess-model_User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/interceptor.ResponseError'
      summary: UserLogin
      tags:
      - User
  /user/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Register user
      parameters:
      - description: User registration data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.UserRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interceptor.ResponseSuccess-model_User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/interceptor.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/interceptor.ResponseError'
      summary: RegisterUser
      tags:
      - User
schemes:
- http
- https
swagger: "2.0"
