basePath: /
definitions:
  interceptor.Empty:
    type: object
  interceptor.ResponseError:
    properties:
      code:
        type: integer
      err:
        items:
          type: string
        type: array
      message:
        type: string
    type: object
  interceptor.ResponseSuccess-interceptor_Empty:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/interceptor.Empty'
      message:
        type: string
    type: object
  interceptor.ResponseSuccess-model_Test:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/model.Test'
      message:
        type: string
    type: object
  model.Test:
    type: object
host: localhost:8080
info:
  contact: {}
  description: Gin study is a small project for beginners to learn by writing a blog
    built by the gin framework.
  title: Gin Study API
  version: 1.0.1
paths:
  /test:
    get:
      description: Test ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interceptor.ResponseSuccess-interceptor_Empty'
      summary: Ping
      tags:
      - Test
    post:
      consumes:
      - application/json
      description: Test pong
      parameters:
      - description: Test data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Test'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interceptor.ResponseSuccess-model_Test'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/interceptor.ResponseError'
      summary: Pong
      tags:
      - Test
  /test/sentVerificationCode:
    get:
      description: Sent verification code
      parameters:
      - description: Phone number
        in: query
        name: phone_number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interceptor.ResponseSuccess-interceptor_Empty'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/interceptor.ResponseError'
      summary: SentVerificationCode
      tags:
      - Test
schemes:
- http
- https
swagger: "2.0"
